set_arm_mode:
  name: Set Arm Mode
  description: "Set arming mode for the camera"
  target:
    entity:
      integration: securityspy
      domain: camera
  fields:
    mode:
      name: Armed Mode
      description: "(Required) Valid options are: continuous = Enable/Disable Continuous Recording, on_motion = Enable/Disable motion recording, action = Enable/Disable Actions."
      required: true
      example: on_motion
      selector:
        select:
          options:
            - "continuous"
            - "on_motion"
            - "action"
    enabled:
      name: Enabled
      description: "(Required) True or false"
      required: true
      example: True
      selector:
        boolean:
enable_schedule_preset:
  name: Enable Schedule Preset
  description: "Activate a specific Schedule Preset"
  fields:
    preset_id:
      name: Schedule Preset ID
      description: "The ID of the Schedule Preset to enable. (See Camera Attributes for a list.)"
      required: true
      example: "1214161810"
      selector:
        text:
    config_entry_id:
      name: Config entry ID
      description: "Optional SecuritySpy config entry ID. Required when more than one SecuritySpy server is loaded."
      required: false
      selector:
        text:
download_latest_motion_recording:
  name: Download latest motion recording
  description: "Download the latest motion recording video to Home Assistant"
  target:
    entity:
      integration: securityspy
      domain: camera
  fields:
    filename:
      name: Filename
      description: "Enter directory and filename where to store the video in Home Assistant"
      required: true
      example: "/media/motion_recording.mv4"
      selector:
        text:
